CREATE TABLE IF NOT EXISTS campuses (id BIGINT PRIMARY KEY, code VARCHAR(10) UNIQUE NOT NULL, name TEXT NOT NULL, city TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS students (id BIGSERIAL PRIMARY KEY, roll_no VARCHAR(40) NOT NULL CONSTRAINT uq_students_roll_no UNIQUE, first_name TEXT NOT NULL, last_name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, campus_id BIGINT REFERENCES campuses(id), department TEXT NOT NULL, year_of_study SMALLINT NOT NULL, attendance NUMERIC(5,2) DEFAULT 100, cgpa NUMERIC(3,2) DEFAULT 0, updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS courses (id BIGSERIAL PRIMARY KEY, code VARCHAR(20) UNIQUE NOT NULL, title TEXT NOT NULL, description TEXT, department TEXT NOT NULL, credits SMALLINT NOT NULL, campus_id BIGINT REFERENCES campuses(id), updated_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS enrollments (id BIGSERIAL PRIMARY KEY, student_id BIGINT REFERENCES students(id), course_id BIGINT REFERENCES courses(id), semester VARCHAR(30), grade VARCHAR(3), score NUMERIC(5,2), UNIQUE(student_id, course_id, semester));
ALTER TABLE students REPLICA IDENTITY FULL;
ALTER TABLE courses REPLICA IDENTITY FULL;
ALTER TABLE enrollments REPLICA IDENTITY FULL;
INSERT INTO campuses VALUES (1,'PUN','Pune Institute of Technology','Pune') ON CONFLICT DO NOTHING;
